Samillion/ModernZ

- README.md
- modernz.lua
Fix in `modernz.lua`:
- Properly close ASS tags
- Alpha shade not showing on full screen with --border=yes
- Interactive lists hiding behind OSC on pause
- Decrease "show/hide" zone above OSC while user_opts.bottomhover
- Window controls not working while paused and pinned
`README.md`:
Remove to-do list. Keep it in issues, to not spam README.md commits
> Fix alpha shade, window controls, ASS tags, interactive lists, hover zone

- modernz.lua
I noticed the time display was always showing hours even for short videos (like 00:25:59 for a 25-minute video), which felt a bit cluttered and always bothered me. Most other players like YouTube only show hours when needed, so I thought we could do the same.
- Short videos: 03:24 instead of 00:03:24
- Long videos: still 01:23:45 (no change)
- Everything else (milliseconds toggle, remaining time) works exactly the same
Let me know what you think!
> feat: dynamic time format based on video duration

- README.md
- docs/CONTROLS.md
- docs/TRANSLATIONS.md
- docs/USER_OPTS.md
This pull request refactors the existing README by splitting it into smaller sections, which are now located in a newly created /docs folder. The README was starting to become huge, so I wanted to tidy things up and improve readability and navigation.
- Restructured the README for clarity and conciseness.
- Moved lengthy sections into separate Markdown files under /docs.
- Updated links and references to ensure they point to the new locations.
Feel free to change anything or tweak it as you see fit - these are just a few ideas I came up with.
> Refactor README: Organize Sections into /docs Folder

- extras/README.md
- extras/pause_indicator_lite.lua
| Option                 | Value       | Description                                                                                                                                   |
|------------------------|-------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| `flash_play_icon`      | true        | Flash play icon on unpause? (best with pause indicator icon)                                                                                  |
| `flash_icon_timeout`   | 0.3         | How long should the flash last? (seconds)                                                                                                     |
| `flash_icon_bigger_by` | 0           | Increase flash …
> pause indicator: add option to flash play icon on unpause

- modernz.lua
This PR addresses the inconsistency where the seekbar tooltip wasn't following the same time format as the rest of the OSC.
- MM:SS only when seeking positions under 1 hour (e.g., 05:30)
- HH:MM:SS when seeking past 1-hour positions (e.g., 01:23:45)
This matches how the main time display works and follows the behavior of popular video players like YouTube.
Closes #62
> fix: apply dynamic time format to seekbar tooltip (#62)

- modernz.lua
- Add user_opts.time_format to control time display format
- "dynamic" (default): Shows MM:SS for sub-hour content
- "fixed": Always shows HH:MM:SS for consistency
Fixes #63
> feat: add configurable time format option

- modernz.lua
As requested in #104, this makes it so the time shown by the seekbar is affected by the `time_format` property.
Preview:
> fix: sync seekbar time format with time_format option

- docs/CONTROLS.md
- modernz.lua
Useful for auto-profiles in `mpv.conf`, idea by @Keith94 
**Example to set persistent progress bar automatically:**
```ini
[Persistent-Bar]
profile-desc=Enable persistent bar on window pin or fullscreen
profile-cond=ontop and ontop == true or fullscreen
profile-restore=copy-equal
input-commands=script-message-to modernz persistent-progress yes
[Persistent-Bar-Off]
profile-desc=Disable persistent bar when not pinned or not fullscreen
profile-cond=not ontop or ontop == false or not fullscreen
profile-restore=copy-equal
input-commands=script-message-to modernz persistent-progress no
> feat: add a script-message for persistent progress bar

- modernz.conf
- modernz.lua
This PR updates the OSC scale calculation code to match upstreams, ensuring that the `osd-scale-by-window` property is respected. This also requires changing `vidscale`'s default from `true` to `auto`. However, since `osd-scale-by-window` defaults to `true`, there are no changes to users with the default config.
**Changes**
---
`vidscale` now defaults to `"auto"`, which respects the `osd-scale-by-window` property (which by default is `true`)
**Preview**
---
| auto                                                                                               | yes                                                                                               | no                                                                                               | …
> fix: osc scaling behavior

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
This PR adds an alternate style for hovered buttons.
- `hovereffect` is no longer a boolean but a string corresponding to a hover effect (`glow`, `size`). Deafault is `glow`
- `hovereffect` is now disabled by leaving it blank or setting it to an unsupported value.
- Added the `size` hover effect which scales hovered buttons
- Added `hover_button_size` which is the scale applied to hovered buttons when `hovereffect` is set to `size`. Default is 115%
https://github.com/user-attachments/assets/17f71e17-ac33-471e-9851-01c118809eca
> add hovereffect `size`

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
That way, the user doesn't have to edit/adjust `ytdl-format` in yet another config file.
The download button will simply grab the same video format (quality), as the current `ytdl-format` or the default one set by mpv which is `bestvideo+bestaudio/best` [[reference](https://mpv.io/manual/master/#options-ytdl-format)]
This is useful for users that utilize scripts such as [ytdlAuto-Format](https://github.com/Samillion/mpv-ytdlautoformat) or [quality-menu](https://github.com/christoph-heinrich/mpv-quality-menu), which will allow them to download the video right away with the current viewing `ytdl-format` set by such format controller scripts.
> refactor: download button to use current or default ytdl-format

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
This PR adds a new `color` hovereffect (should solve #130) and allows the user to use multiple hovereffects.
It also adds a configuration for the glow amount which should make all hovereffect properties changeable in config.
- `hovereffect` is now a comma seperated list with possible values of: `glow`, `size` and `color`
- Added `hovereffect_color` which is the hex color applied when using the `color` hovereffect
- Added `button_glow_amount` which alters the glow/blur applied by the `glow` hovereffect
Previews of all hover effects together.
https://github.com/user-attachments/assets/e1b2adbf-67e2-4bec-a311-49083dfb6786
https://github.com/user-attachments/assets/fda194bd-460e-4c86-9f57-82a4fc08786c
> feat: support for multiple hovereffects, color hovereffect & customizable glow amount

- modernz.lua
Currently, the OSC style variables use a mix of different variable naming conventions, which is most likely due to how many people have worked on the project over the years. This commit standardizes them to use snake care, as well as removes some redundant string concatenation.
> refactor: rename osc styles

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
This PR adds button bar decluttering options for the playlist button and tooltips.
- Added `hide_empty_playlist_button` which hides the playlist button when no playlist exists.
- Added `gray_empty_playlist_button` which grays out the playlist button when no playlist exists. Which should solve #129.
- Added `tooltips_for_disabled_elements` which disables tooltips for disabled/grayed out buttons. E.g. the sub track button when no subtitles are available.
- Added `tooltip_hints` which toggles the clarification tooltips of the information, loop, ontop and screenshot buttons.
> Add button bar decluttering options (playlist & tooltips)

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
- Added `hovereffect_for_sliders` option which when enabled will apply hovereffects to slide handles (volume & seek bar). This does **not** apply the glow effect as it would not be visible.
https://github.com/user-attachments/assets/5f5bc75a-a878-45e3-98e7-656c746fbd0a
> feat: option to apply hovereffects to slide handles

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Makes it match osc.lua defaults.
> refactor: update title formatting

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Pinging: @Commander07 @Keith94 
**Note:** This isn't mandotary, because I realize personal preference is a factor. That is why I decided not to merge but to first consult with you guys. (original PR maker and requester)
The hover effect size looks great on all elements, except for the following: (looks out of place)
- Title (above seekbar)
- Timestamps (left and right)
- Chapter title (below seekbar)
The size hover effect will be stripped from them.
**Other changes:**
- Tie `elem_ass:append()` to a nested condition, to ensure single action. (ie: in title, it was appending twice, hover and text)
- Restore default value for `hover_button_size` to `115` instead of `110`
- Apply all effects in `hovereffect`
- Change `hovereffect_color` to `#CB7050`, a slightly brighter match with the default …
> refactor: apply all hover effects by default, except for size, limit it

- modernz.lua
If subtitle or audio tracks are disabled manually but are available, the relative icon will gray out to indicate that they're turned off.
> feat: indicate when audio and subtitle tracks are turned off

- README.md
- docs/USER_OPTS.md
- modernz.lua
Initially I was going to reword some comments for clarity but ended up reordering the user options as well. The reordering reflects my personal preference on what I think makes sense, so I'm open to feedback on whether this approach is effective or if there are better ways to structure it.
- Updated the header comment: Added licensing information and provided some info, aligning it with standard practices seen in other scripts.
- Made some comments more clear for better understanding, while trying to be consistent.
- Reordered and regrouped the user options.
- Changed the "log" value to "logarithmic" for consistency.
I considered splitting the buttons group into two distinct groups: one for showing and hiding buttons and another for the button functionality settings. It would look …
> docs: reorder user options and improve comments for clarity

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
This is to prevent accidental clicks on chapter title select menu. (below seekbar)
> refactor: change event respond for chapter title to up press instead of down

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
- Disables irrelevant elements (play/pause, jump, loop, screenshot, seekbar and time display) for images.
- Removes hover effects from disabled sliders to match button behavior.
- Adds `hide_elements_for_image` which when enabled will hide irrelevant elements for images
> feat: disable irrelevant elements for images

- modernz.lua
Pinging @Commander07 and @ctlaltdefeat
There is a gap at the end of the seekbar, because the cache color doesn't address the handle size
| Before | After |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/a2172bbe-4ecb-477a-bd34-840dff0929e8) | ![After](https://github.com/user-attachments/assets/6713b368-3f76-4f01-b8c2-2670cf97d1b3) |
**Test with:** 
- [dev_slider_gap_fill/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_slider_gap_fill/modernz.lua)
**Changes:**
```diff
- elem_ass:rect_cw(pstart, slider_lo.gap, pend, elem_geo.h - slider_lo.gap)
+ elem_ass:rect_cw(pstart - rh, slider_lo.gap, pend + rh, elem_geo.h - slider_lo.gap)
```
> fix: correctly fill cache color in slider

- modernz.lua
Changes the way `new_file_flag` is handled to avoid it being triggered on backwards seeking. Should close #164.
> fix: `osc_on_seek` not triggering for backwards seeking

- modernz.lua
Checks if `loopinpause` when right clicking play/pause button. Should close #165.
> fix: `loopinpause` not being checked

- modernz.lua
Pinging @Commander07 
Pinging @Xurdejl and @Keith94 as well.
Terribly sorry for the bother. Only if you can, could you help me test this please?
This is a restructure of https://github.com/Samillion/ModernZ/pull/158
**Now there are two layouts:**
- `modern`
- `modern-image`
**Handled with:**
```lua
-- load layout
is_image() -- init check if it's an image file
if state.is_image then
layouts["modern-image"]()
else
layouts["modern"]()
end
```
**The `is_image()` function determines if the file is an image or not:**
```lua
local function is_image()
local current_track = mp.get_property_native("current-tracks/video")
if current_track and current_track.image and not current_track.albumart 
and mp.get_property_number("estimated-frame-count", 0) < 2 and audio_track_count == 0 then
state.is_image = …
```
> feat: add dedicated layout for image mode

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Pinging: @Commander07 @Keith94 @Xurdejl 
Ok, so I merged the main layouts, now focusing on improving the looks of things.
**Changes:**
- Title width should now be handled and displayed better with extremely long filenames
- Playlist button and skip buttons should have better visibility now
**To do:**
- Anything else?
Test script: [/dev_modernimage_refactor/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_modernimage_refactor/modernz.lua)
> refactor: modern-image layout title width and elements visibility

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
**Reason:**
Many of the user options were remnants of the past and edited/added by multiple people, which made it seem random.
This ensures consistency and readability, to make you understand what the option does just by its label.
> BREAKING: rename many user options

- modernz.lua
This PR aims to reduce code duplication and complexity by separating slider seekrange & handle drawing from the rest of the slider. As a result seekrange drawing is now the same on both the normal and persistent seekbar which closes #173.
- Created `draw_slider_handle` function which takes an element its ass and draws a handle using settings provided by `user_opts`.
- Created `draw_slider_seekranges` function which takes an element its ass and draws seekranges using settings provided by `user_opts`.
- Changed both sliders and the persistent seekbar to use the new functions,
Persistent seekbar now respects `user_opts.seekbar_cache_color`
> refactor: move slider seekranges & handle drawing into own functions

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
The blur level has been set to 100 ever since the `Modern` origin was made, which is fine for most users. However, this is highly dependent on CPU, and some computers might have a slow render time because of it.
Now the user can easily adjust it to their suitable level in `modernz.conf`.
**Example:** (slow render)
Thanks to @guidocella for the screenshot and @kasper93 for noting that blur amount (strength) is the cause.
**Details:** (search for `\blur`)
https://aegisub.org/docs/latest/ass_tags/
>Quote:  Be careful, setting strength too high can take a lot of CPU time to render.
> feat: add option to control blur amount for background alpha

- .github/ISSUE_TEMPLATE/2_bug_report.yml
- .github/PULL_REQUEST_TEMPLATE
- README.md
- docs/CONTROLS.md
- modernz.lua
The value 0.3 is the minimum to draw a circle radius that would cover the seek bar.
> fix: validate seek handle size with a minimum value of 0.3

- .gitattributes
The previous .gitattributes was causing unexpected behaviour, such as showing unsaved changes after a fresh clone.
According to the [documentation](http://git-scm.com/docs/gitattributes#_end_of_line_conversion), `* text=auto` ensures that all text files in the repository will have consistent LF line endings. Therefore, the `* text eol=lf` line is unnecessary and can be removed.
GitHub Linguist is case-sensitive when identifying languages. The correct alias for EditorConfig is "editor-config". Using lowercase will not be recognized.
For reference: [linguist/languages.yml](https://github.com/github-linguist/linguist/blob/f164d13fa618023ecf2d8f2ed9a6ce5fae731346/lib/linguist/languages.yml#L1842-L1850)
> fix(gitattributes): enforce LF line endings and fix Linguist language

- modernz.lua
Updated `window_controls_enabled` logic to ensure window controls are visible when `window_top_bar = "yes"`, by including the `top_titlebar` condition.
Fixes #228, fixes #229
> fix: window controls fade alpha and hide behaviour (#228, #229)

- modernz.lua
This PR introduces a new user option, `handle_always_visible`, to control the visibility of the slider handles (progress bar, volume, etc.).
- When `handle_always_visible` is set to `"true"`, the slider handle remains visible at all times, following the previous behaviour.
- When `handle_always_visible` is set to `"false"`, the handle will only be visible when the user hovers over the slider, just like YouTube, Spotify, etc.
> Feat: make slider handle hover-only with user option

- modernz.lua
This PR makes sure to ignore the `ignore` command in `command_callback`. Closes #227.
> fix: `ignore` command being ignored

- modernz.lua
When track IDs are auto `mp.get_property_native()` returns `auto`, but `mp.get_property_number()` returns `nil`.
Refrence: [osc.lua#15507](https://github.com/mpv-player/mpv/pull/15507)
> refactor: improve track ID retrival

- docs/USER_OPTS.md
- modernz.lua
Changed the title commands again to match mpv standard. `cycle audio` and `cycle sub` show an `osd-msg` by default, so I removed that bit of unneeded text.
> refactor: changed default actions for some commands

- modernz.lua
Stop setting the `z` level of the OSC overlay. This prevents the console/select menu from being drawn below the layout when clicking buttons
> fix: don't place the overlay above other ones

- README.md
- docs/CONTROLS.md
- docs/INTERACTIVE_MENUS.md
- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/208
The issue also details the progress and changes made throughout the OSC.
> feat: reduce OSC footprint by making it more compact

- docs/USER_OPTS.md
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/273
```EditorConfig
nibbles_top=yes
nibbles_bottom=yes
```
> feat: add options to control chapter markers on seekbar

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/278
> fix: if volume value contains decimals, only show one

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Two styles:
* existing triangle style
* More subtle bar style
Also slider gap should be computed from seekbar background height and seekbar height instead of redefining.
> feat: add more chapter marker styles with nibbles_style

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/285
- If `show_title` and `show_chapter_title` are disabled and `thumbfast` is not used, show hovered chapter title above the time code tooltip instead of appending it in the same time code line
- Align a min and max value so that on hover on end/start, chapter title tooltip doesn't go out of bound
- if `show_title` and `thumbfast` are disabled, but `show_chapter_title` is enabled, replace `chapter_title` with hovered chapter. Similar to how `title` is changed on chapter hover, if `show_title` is enabled and `thumbfast` is disabled.
> feat: improve hovered chapter display if thumbfast is disabled

- modernz.lua
This addresses the following scenarios:
- `audio_track=true` + `volume_control=yes`
- `audio_track=true` + `volume_control=no`
- `audio_track=false` (no audio or volume elements)
- short window width + `audio_track=true` + `volume_control=yes` (give time codes priority over volume bar)
> fix: properly display time codes in different audio scenarios

- modernz.lua
Instead of hiding the time codes, move them above play controls, centered.
Centered above play controls is the best fit, as these buttons do not have tooltips and places the essential elements centered so even in abnormal narrow videos or window, they're displayed.
https://github.com/user-attachments/assets/07cb8d32-06b8-44e3-93e9-d13ce5888b8d
> fix: don't hide time codes in portrait or narrow window

- extras/pause-indicator-lite/README.md
- extras/pause-indicator-lite/pause_indicator_lite.conf
- extras/pause-indicator-lite/pause_indicator_lite.lua
The ability to use `pause_indicator_lite.conf` in `script-opts` to avoid having to change option values with every update.
> pause-indicator: add use of config file and minor improvements

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/302
- Use osc margins to show select menus and console above osc, when `visibility=always`
- Change z depth of osc to `1000` instead of `-1`
- When osc is visible, don't spam margins (verbose)
- Don't force hide osc with menus if osc visibility is set to always
- Remove unnecessary `request_init()` calls within `osc_init()`
- Apply osc margins within `osc_init()`
- Add `cache_enabled()` helper
- Don't use margins if osc is visible only temporarily
- Update chapter title to the current playing chapter
- Since `request_init()` was used to update it (not sure why), it stopped working after its removal. Simply letting the content function handle it resolves the issue.
- Show `cache_info` tooltip on hover using the new cache helper function
> feat: when osc visibility is set to always, apply osc margins to show menus above it

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
`cache_info` is now a single element, which displays cached time and cache speed per second, depending on user options.
This improves the overall visibility and control of the element and its tooltip, and now also has functionality to display the cache page from stats info on click.
> feat: add click function to cache_info and improve its display

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/314
> fix: don't inherit osd alpha style on button tooltips

- README.md
- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/108
**Changes**:
- Added options to control thumbnail border radius
- Added option to control thumbnail border outline color
- Changed `thumbnail_border` to `3` instead of `2`
```EditorConfig
thumbnail_border_outline=#404040
thumbnail_border_radius=3
```
> feat: add options for thumbnail rounded corners and outline color

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/307
**Changes**:
- Remove deprecated `title_bar_box` option
- Fix `window_fade_alpha` behavior to work properly. (0 to disable)
- Add `window_fade_blur_strength` to control window bar blur strength separately from osc
```EditorConfig
window_fade_alpha=75
window_fade_blur_strength=100
```
> feat: add options to control window bar alpha

- modernz.lua
The old `modern-osc` implementation of this is kind of weird. It worked, but not in the best way.
**Old behavior**:
- `showonpause` and `paused` then trigger `show_osc()`
- `keeponpause` and `paused` force no `hide_osc()` and force constant call of `show_osc()`
Which is ineffective because that behavior even with `keeponpause` enabled and `paused`, on mouse leave the osc will hide.
This fix unites `showonpause` and `keeponpause` into one function within observing the pause property instead of altering auto hide behavior.
Also, it changes `keeponpause` behavior so that it changes visibility to `always` temporarilty while paused, instead of forcing to not call `hide_osc()` and spam calling `show_osc()`
> fix: don't hide osc on mouse leave when paused and keeponpause

- modernz.lua
The problem was that sometimes the thumbnail background and title would overlap with each other.
This is because they have the same layer level, which by default is 50.
```lua
-- set layout defaults
elements[name].layout.layer = 50
```
Instead of randomly assigning a high layer number to seekbar, be consistent and simply increment by one.
```PowerShell
PS C:\> mpv 'E:\clips\test_video.mp4'
modernz: Seekbar layer: 51
modernz: Title layer: 50
modernz: Chapter layer: 50
```
This should fix thumbnail and title overlapping, because the thumbnail is generated as a seekbar tooltip, and now it will have a higher layer level.
In the future I might implement an automated increment to seekbar layer, by using something like:
```lua
lo.layer = lo.layer + 1
```
As of now, this change should suffice, as …
> fix: be consistent with seekbar and thumbnail layer instead of assigning random layer levels

- README.md
- docs/INTERACTIVE_MENUS.md
- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
**Changes**:
- Use modern icons for window controls (close, maximize, minimize) using the fluent icons to match the osc
- Apply size hover effects to window controls
- Add hover color options for each window control button instead of combining min/max
- Minor and general refactoring
```EditorConfig
windowcontrols_close_hover=#F45C5B
windowcontrols_max_hover=#F8BC3A
windowcontrols_min_hover=#43CB44
```
> feat: modernize window controls icons and apply size hover effects to them

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
**Changes**:
- Improve time codes hitbox in different scenarios
- Improve narrow window trigger
**Known issues**: [old issues, not caused by this PR]
- Hitbox width will not be accurate if font size for time codes changes drastically
- Introduce width offset for user to control as an option in the future? ie: `10` or `-10`
- ~~Using `time_format=dynamic`, with a video longer than one hour, once playback time reaches one hour or more, the hitbox doesn't get changed to match.~~
- ~~If you invoke milliseconds (right click) on/off, it is fixed~~
- ~~This hints that hitbox value isn't updated and needs a measure to `request_init()`, which is very expensive with playback time~~
- ~~I don't want to rush implementing a fix for this, so it will be added in a separate PR when a proper method is …
> fix: improve time codes hitbox and narrow window visibility

- extras/pause-indicator-lite/README.md
- extras/pause-indicator-lite/pause_indicator_lite.conf
- extras/pause-indicator-lite/pause_indicator_lite.lua
- add `fluent_icon_size` option
The `fluent_icons` option requires the [fluent-system-icons.ttf](https://github.com/Samillion/ModernZ/blob/main/fluent-system-icons.ttf) font file, which is also used for ModernZ osc.
- To use the fluent icon style, set `fluent_icons` to `yes`
- To control icon size, adjust `fluent_icon_size` value, default is `90`
- Respects icon style options: `icon_color`, `icon_border_color`, `icon_border_width`, `icon_opacity`
```
mpv
├── fonts/
│   └── fluent-system-icons.ttf (optional) [required for fluent_icons]
├── script-opts
│   └── pause_indicator_lite.conf
└── scripts
└── pause_indicator_lite.lua
```
> pause-indicator: add fluent_icon_size option

- README.md
- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
- Add `visibility_modes` option
- Default: `never_auto_always`
- The list of visibility modes to cycle through when calling the `osc-visibility cycle` script message
- Modes are separated by `_`
```EditorConfig
visibility_modes=always_never
```
```EditorConfig
v  script-message-to modernz osc-visibility cycle
```
From upstream mpv: https://github.com/mpv-player/mpv/pull/15734
> feat: add visibility_modes option

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/306
Force show seekbar tooltip (ie: thumbnail) on mouse drag, even if not hovering seekbar, while holding down mouse button.
- Add `force_seek_tooltip` option
- Rename `playingWhilstSeeking` state to `playing_and_seeking`
- Rename `persistentprogresstoggle` state to `persistent_progress_toggle`
- Remove unused state `playingWhilstSeekingWaitingForEnd`
- Make `playing_and_seeking` state independent and not tied to `mouse_seek_pause` option
- Fix behavior of  `mouse_seek_pause` option when set to `no` and mouse drag then release mouse button
- It used to pause the video on button release, now it doesn't
- Now it only cycles pause if `mouse_seek_pause` is set to `yes`
```EditorConfig
force_seek_tooltip=yes
```
> feat: add force_seek_tooltip option

- modernz.lua
refactor: strip trailing whitespace
refactor: don't register a shutdown handler
shutdown is sent when mpv quits, but also to builtin script unloaded at
runtime with e.g. set osc no. There is no need to unset properties at
shutdown for external scripts since they only receive it on quit.
> refactor: don't register a shutdown handler

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/341
If `osc_on_seek` is enabled, don't hide osc while seeking by registering a seek event and remove it properly
> fix: if osc_on_seek is enabled, don't hide osc while seeking

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
- Add `osc_on_start` option to show osc on start of every file
```EditorConfig
osc_on_start=yes
```
Fixes: https://github.com/Samillion/ModernZ/issues/345
> feat: add osc_on_start option

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
- Add `info_mbtn_left_command` option
```EditorConfig
info_mbtn_left_command=script-binding stats/display-page-1-toggle
```
Alternatively, you can use the default stats info command
```EditorConfig
info_mbtn_left_command=script-binding stats/display-stats-toggle
```
Fixes: https://github.com/Samillion/ModernZ/issues/351
> feat: add info_mbtn_left_command option

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Based on mpv 0.40 changes.
left-click = show file and track info
middle-click = show the path
right-click = open the history selector
> refactor: bind right clicking the title to show history

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Add two new options: 
- `fade_transparency_strength`
- `window_fade_transparency_strength`
This adds more customization to the fade options and can be used to create a transparency box for the top and bottom of the OSC.
Edit: Config settings example
**Botton box**
```EditorConfig
fade_alpha=80
fade_blur_strength=0
fade_transparency_strength=75
```
**Top box**
```EditorConfig
window_fade_alpha=152
window_fade_blur_strength=0
window_fade_transparency_strength=75
```
> feat: add osc transparency options

- modernz.lua
> This ensures that the next/previous buttons are appropriately enabled/disabled when the position of the currently playing entry is changed.
Reference: https://github.com/mpv-player/mpv/pull/16244
> fix: update playlist position on change

- README.md
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/370
- Respect manual `sub-pos` by user during playback all while maintaining show/hide osc sub rise.
- Don't adjust subtitle position if user's `sub-pos` is higher (on screen) than the raise factor when osc is visible
- Simplify scale logic into a variable
> fix: respect manual sub-pos by user during playback

- extras/pause-indicator-lite/README.md
- extras/pause-indicator-lite/pause_indicator_lite.conf
- extras/pause-indicator-lite/pause_indicator_lite.lua
Add options to show an indicator on mute and control position of mute indicator
- `mute_indicator`
- `mute_indicator_pos`
Adjust the following options in `pause_indicator_lite.conf`
```EditorConfig
mute_indicator=no
mute_indicator_pos=middle_left
```
Fixes: https://github.com/Samillion/ModernZ/issues/361
> pause-indicator: add mute indicator options
