- modernz.lua
> Allow scroll wheel to seek when hovering on seekbar

- modernz.lua
> Adjust raised sub based on user_opts scale

- modernz.lua
> Correctly hide OSC buttons if no room to show them

- modernz.conf
- modernz.lua
> Do not use /no-ext by default as it could produce an error

- README.md
- modernz.conf
- modernz.lua
> Add user option to show/hide the previous/next playlist track buttons

- README.md
- modernz.conf
- modernz.lua
> Add user option to show/hide fullscreen toggle button

- modernz.lua
> Do not show volumebar tooltip if no audio tracks are available

- README.md
- modernz.conf
- modernz.lua
fixes #37 
PR Reference:  https://github.com/mpv-player/mpv/pull/15031
Guido's solution is excellent. It makes the hesitation go away, because now the user has full control, we merely set the default behavior.
> Add user options for mouse actions on buttons

- README.md
- modernz.conf
- modernz.lua
> Add user option to match volume bar color with seekbar color

- modernz.conf
> Fix playlist button comment

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
> Add option to control pause state while seeking with mouse move

- modernz.lua
> Allow osc to hide properly with bottomhover off

- modernz.lua
To match my PR at mpv https://github.com/mpv-player/mpv/pull/15148 and https://github.com/Samillion/ModernZ/pull/76#issuecomment-2427978811
> cleanup: replace escaped quotes, remove unneeded parentheses

- modernz.lua
Also, fix subtitle position in screenshot with `subtitle+each-frame` flag
> syntax: simplify logic where possible and be consistent

- modernz.lua
This is a user option from the vanilla mpv osc.
> Feat: add windowcontrols_title user option

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
- Added `seek_resets_hidetimeout` which controls if seeking should reset the OSC hide timeout. Should close #149.
> feat: add `seek_resets_hidetimeout` option

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
- Added `seekbar_cache_color` which sets the color of the cache ranges. Should close #148.
> feat: add `seekbar_cache_color` option

- modernz.lua
Reference: https://github.com/mpv-player/mpv/pull/15265
> fix: observe playlist-count instead of playlist property

- modernz.lua
16 was too thin, 20 was too thick. 18 is just right.
> refactor: decrease height of seekbar from 20 to 18

- README.md
- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
```
windowcontrols_close_hover=#E81123
windowcontrols_minmax_hover=#FFD700
```
> feat: add hover color options for window controls

- modernz.lua
Right-clicking playlist opens select menu.
Also implement right-click FS to toggle maximize: https://github.com/mpv-player/mpv/pull/15157
> refactor: change right-click functions for playlist and fullscreen

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Based on https://github.com/mpv-player/mpv/blob/master/DOCS/man/osc.rst
> feat: add additional mouse functions for buttons

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/270#issuecomment-2564300438
> fix: make progress-toggle work with persistentprogress=yes

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/279
Fixes: https://github.com/Samillion/ModernZ/issues/282
> fix: give priority to time codes visibility over volume bar

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/239
> fix: display seek ranges correctly when seek_handle_size is 0

- extras/pause-indicator-lite/README.md
- extras/pause-indicator-lite/pause_indicator_lite.lua
Reference: https://github.com/Samillion/ModernZ/issues/291
> pause-indicator: add keybind_eof_disable option

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/230
> fix: respect hide timeout on pause cycle when showonpause=yes

- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/270
> fix: don't freeze osc on fast visibility cycle

- docs/INTERACTIVE_MENUS.md
- docs/USER_OPTS.md
- modernz.conf
Thanks to @Keith94 for notifying that docs and config file weren't updated to the recent changes.
> docs: update hover_effect_color to match recent changes

- docs/USER_OPTS.md
- modernz.lua
Fixes: https://github.com/Samillion/ModernZ/issues/327
> fix: always show first stats page with info_button

- extras/locale/modernz-locale.json
A typo has been fixed in stats_info
> locale: fix stats_info Russian translation phrase

- docs/INTERACTIVE_MENUS.md
Huge thanks to @guidocella for his work on `select.lua` and `console.lua`, genuinely introduced some much needed QoL features to mpv, and now with a great aesthetic as well.
> docs: update select menus preview

- extras/locale/modernz-locale.json
- modernz.conf
- modernz.lua
Dynamically compute positions and visibility of left and right buttons (for video only).
This should make adding and moving around buttons easier.
> refactor: button positioning for easier addition and shuffling of buttons

- docs/USER_OPTS.md
- modernz.conf
- modernz.lua
> feat: option to hide osc while cursor is in bounds

- modernz.lua
> feat: make window controls glow on hover
